version: "3"
services:

    # Nginx
    webserver:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - './:/usr/share/nginx/html'
            - './docker/nginx-conf/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - php
        command: [nginx-debug, '-g', 'daemon off;']

    # PHP:8.2-fpm
    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                APP_ENV: '${APP_ENV}'
        container_name: php
        environment:
            APP_ENV: '${APP_ENV}'
            CONTAINER_ROLE: 'app'
        depends_on:
            - database
        expose:
            - 9000

    # MySQL
    database:
        image: 'mysql:8.0'
        container_name: database
        ports:
            -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            -   'dbdata:/var/lib/mysql'
            -   './docker/create-database.sh:/docker-entrypoint-initdb.d/create-database.sh'

#Volumes
volumes:
    dbdata:
        driver: local
